# Generated by Django 3.0.8 on 2020-07-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200710_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_purchases',
            field=models.IntegerField(default=0, verbose_name='колличество в магазине'),
        ),
    ]
