# Generated by Django 3.0.8 on 2020-07-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200710_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/no_image.png', null=True, upload_to='product_image', verbose_name='изображение товара'),
        ),
    ]
